name: Visual Regression Testing Report

on:
  pull_request:
    paths:
      - 'webview/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  vrt-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'webview/package-lock.json'

      - name: Install dependencies
        run: |
          cd webview
          npm ci

      - name: Run VRT tests
        run: |
          cd webview
          npm run test:browser -- --reporter=json --outputFile=./test/report.json --run
        continue-on-error: true

      - name: Upload VRT screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vrt-screenshots
          path: |
            webview/.vitest-attachments/**/*.png
            webview/test/vrt/__screenshots__/**/*.png
          retention-days: 7

      - name: Report test results
        uses: ctrf-io/github-test-reporter@v1
        if: always()
        with:
          report-path: webview/test/report-ctrf.json
          title: '📸 Visual Regression Test Report'
          pull-request-report: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment VRT Screenshots
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { commentVRTScreenshots } = require('./.github/workflows/scripts/comment-vrt-screenshots.js');
            await commentVRTScreenshots(context, github);
